Received: from LV3PR10MB8177.namprd10.prod.outlook.com (2603:10b6:408:289::17)
 by BYAPR10MB2616.namprd10.prod.outlook.com with HTTPS; Wed, 8 Apr 2026
 23:26:30 +0000
Received: from SA9PR13CA0046.namprd13.prod.outlook.com (2603:10b6:806:22::21)
 by LV3PR10MB8177.namprd10.prod.outlook.com (2603:10b6:408:289::17) with
 Microsoft SMTP Server (version=TLS1_2,
 cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id 15.20.9769.18; Wed, 8 Apr
 2026 23:21:26 +0000
Received: from SA2PEPF000015C9.namprd03.prod.outlook.com
 (2603:10b6:806:22:cafe::68) by SA9PR13CA0046.outlook.office365.com
 (2603:10b6:806:22::21) with Microsoft SMTP Server (version=TLS1_3,
 cipher=TLS_AES_256_GCM_SHA384) id 15.20.9769.38 via Frontend Transport; Wed,
 8 Apr 2026 23:21:26 +0000
Authentication-Results: spf=permerror (sender IP is 103.102.152.108)
 smtp.mailfrom=kirimdata.id; dkim=none (message not signed)
 header.d=none;dmarc=none action=none
 header.from=iaesjournal.com;compauth=fail reason=001
Received-SPF: PermError (protection.outlook.com: domain of kirimdata.id used
 an invalid SPF mechanism)
Received: from mail.kirimdata.id (103.102.152.108) by
 SA2PEPF000015C9.mail.protection.outlook.com (10.167.241.199) with Microsoft
 SMTP Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id
 15.20.9769.17 via Frontend Transport; Wed, 8 Apr 2026 23:21:24 +0000
Received: from ijece.iaescore.com (unknown [64.202.190.6])
	by mail.kirimdata.id (Postfix) with ESMTPA id 9F6921300;
	Wed,  8 Apr 2026 23:21:19 +0000 (UTC)
To: Engineer =?UTF-8?B?SGVybsOhbiBBbHZlaXJvIEVyYXpv?=
	<haerazog@udistrital.edu.co>
Subject: [IJECE] Submission Acknowledgement
Content-Type: text/plain; charset="utf-8"
X-Mailer: Public Knowledge Project Suite v2
X-Originating-IP: 186.155.17.149
Date: Wed, 8 Apr 2026 23:16:31 +0000
From: "Tole Sutikno" <ijece@iaesjournal.com>
Reply-To: "" <>
Message-ID: <ec712aed-2430-4070-bc36-c5363899a8f5@SA2PEPF000015C9.namprd03.prod.outlook.com>
Return-Path: email@kirimdata.id
X-MS-Exchange-Organization-ExpirationStartTime: 08 Apr 2026 23:21:25.2460
 (UTC)
X-MS-Exchange-Organization-ExpirationStartTimeReason: OriginalSubmit
X-MS-Exchange-Organization-ExpirationInterval: 1:00:00:00.0000000
X-MS-Exchange-Organization-ExpirationIntervalReason: OriginalSubmit
X-MS-Exchange-Organization-Network-Message-Id: 794bd183-2990-404c-1393-08de95c58dc0
X-EOPAttributedMessage: 0
X-EOPTenantAttributedMessage: d51388ef-6ab0-4363-9f94-d56644a45970:0
X-MS-Exchange-Organization-MessageDirectionality: Incoming
X-MS-PublicTrafficType: Email
X-MS-TrafficTypeDiagnostic: SA2PEPF000015C9:EE_|LV3PR10MB8177:EE_|BYAPR10MB2616:EE_
X-MS-Exchange-Organization-AuthSource: SA2PEPF000015C9.namprd03.prod.outlook.com
X-MS-Exchange-Organization-AuthAs: Anonymous
X-MS-Office365-Filtering-Correlation-Id: 794bd183-2990-404c-1393-08de95c58dc0
X-MS-Exchange-AtpMessageProperties: SA|SL
X-MS-Exchange-Organization-SCL: 1
X-Microsoft-Antispam: BCL:0;ARA:13230040|704162111799003|56012099003|16102099003|18002099003|19002099003|55112099003|13003099007;
X-Forefront-Antispam-Report: CIP:103.102.152.108;CTRY:ID;LANG:en;SCL:1;SRV:;IPV:NLI;SFV:NSPM;H:mail.kirimdata.id;PTR:ErrorRetry;CAT:NONE;SFTY:9.25;SFS:(13230040)(704162111799003)(56012099003)(16102099003)(18002099003)(19002099003)(55112099003)(13003099007);DIR:INB;SFTY:9.25;
Content-Transfer-Encoding: quoted-printable
X-MS-Exchange-CrossTenant-OriginalArrivalTime: 08 Apr 2026 23:21:24.7787
 (UTC)
X-MS-Exchange-CrossTenant-Network-Message-Id: 794bd183-2990-404c-1393-08de95c58dc0
X-MS-Exchange-CrossTenant-Id: d51388ef-6ab0-4363-9f94-d56644a45970
X-MS-Exchange-CrossTenant-AuthSource: SA2PEPF000015C9.namprd03.prod.outlook.com
X-MS-Exchange-CrossTenant-AuthAs: Anonymous
X-MS-Exchange-CrossTenant-FromEntityHeader: Internet
X-MS-Exchange-Transport-CrossTenantHeadersStamped: LV3PR10MB8177
X-MS-Exchange-Transport-EndToEndLatency: 00:05:05.3228566
X-MS-Exchange-Processed-By-BccFoldering: 15.20.9769.015
X-Microsoft-Antispam-Mailbox-Delivery:
	wl:1;pcwl:1;ucf:0;jmr:0;auth:0;dest:I;ENG:(910005)(944506478)(944626604)(4710137)(4712097)(4999163)(920097)(811242)(255002)(410001)(930201)(20251009189)(140003);
X-Microsoft-Antispam-Message-Info:
	=?utf-8?B?NjlvS05rQjB6dG1qdHk1VHNPT0VtY0pSV0xaOWgrdXBFOUNrRlR4cHo0TENW?=
 =?utf-8?B?cVdaeVZ1TENaOTRoYlR3TEJpcnQ1bjBtYmtKNjVzRmQyT0FveHdWRTMwZkJo?=
 =?utf-8?B?N1pGRkNDMXljRTdsNTFqc3NQWTVZL0RQNy9KVHlRamsvb0IyZGJQeXRQM0I3?=
 =?utf-8?B?ejNpQXoybDZrTENOUVRjWFl2Z3FxOHV5MlBMTCszWUtNeFJXSER6OXovSmFX?=
 =?utf-8?B?VWJjOXZMVjZQZ2VkVHl5MXQ1dDY1alF6Y28zaW0vdXBJRXhBeEcyNTQweUlD?=
 =?utf-8?B?SDgyZGF5ak4rVzl1QWdrKzNTQlZ3Zk41VndPcUxmMFhUVkFzQm5ZczNVT05l?=
 =?utf-8?B?NG5ibmd4NHUvNUlaYUZKQ213TWVTS2Q5SFh4NExHQ2YxMXBWZDAzMDRxSVRq?=
 =?utf-8?B?V3dBbnhBcHlhV3dnSTYyRCs2WGl6aUZUMHFqQTJkYlNidGFuRnZnak95a0py?=
 =?utf-8?B?emh5WklUUU8vUVRHMmlKSjl2UVlmUCtFeXloMmR3YzhLSTc5VW1pQlFWeTFo?=
 =?utf-8?B?aEpxWVpUN0NveXlwYW1hLzhjWDFBYmc2R2RUNVc4Q3M1SUpwTHQwUS9GQjJC?=
 =?utf-8?B?ZzFuTHE2b0NhUkI2UjlYUlhsK0hVUDM5L1dpMXhmWWJJNHNYWkZIclVMbWFw?=
 =?utf-8?B?TjFnT2xEcXZkWUtJQjNlYUkrTkZJOXArQ3QwMEs5dlNycW5iZmlrbkl3Z0JJ?=
 =?utf-8?B?R3I2WmlTQlZWTU94M0VyejVJc0ZiVXBhYWxNU2lqSlN0ejB2M3FEY05HVHEw?=
 =?utf-8?B?NmI2THNXdG5VQ200OStEMW1BTEYwMU54UFR0K0xwdTJmeFdLV1NaNDg1b1Nt?=
 =?utf-8?B?ckJCcVFlQnY1eE10QVNzV2txUmRYU0lUN2ZpdjdWTDJOeVhBWFdaaUxHMkpw?=
 =?utf-8?B?V3Z3YnUvN1ZtbStId01UMTYxNytpSHFkTHpqUTVIWHVyc2gzeU1mdUpMY084?=
 =?utf-8?B?RlhIRERyZEtmcFlSSkl1VUxNMzVUWk1nK1lvT0dReGV0TGRrVTMxNVE2aTJU?=
 =?utf-8?B?Z0xDTUs3Um1taGduR05aRGtQYkllcUZuZVA2T0xiWVNLZG9maEFON283aDBy?=
 =?utf-8?B?M0Vvbm1jMDNQeE14dTZPNmd4Ry8yRkhLVEJSTWlpUUROL0xrbEZNRHE4b2Jm?=
 =?utf-8?B?azRQVzNtZVM5Yk5RTHFlbmU3RjJlUU15YnBoOGFibUtCTUdobGJxR2M4Ulor?=
 =?utf-8?B?WVFGb0JwRkMxd0l5YmN0QTNXNzNtMzAvcUlFU2tZUWZxemhZcWcvbXROcEp4?=
 =?utf-8?B?c01MREFLVVJZaUVaNFlzcHZVME1JM2llQTdoNFpBMFJ1eEJ0Q2xzT2dMSVMx?=
 =?utf-8?B?dlZXZERhOFdQdTVGTXBYajhJVzZIZ0J1V203KytNWmd4eU02TWcrSmxCdGkv?=
 =?utf-8?B?b053eTVmaFd2UHVaYVJicVFlOTV1V2E5VU1oNnhycWlhZ0l0Q05lM1JpZ29R?=
 =?utf-8?B?NWVvVmhjdmJkcGlIS3VvRWI5NDc5cGtYaDRrUXNscElicElueFFSZzN6MGZU?=
 =?utf-8?B?TTcvSDIweXJNaER4TzhPMXQ0bDhxSklkWVRvSFhpQ2ovRU1wamlHRGNLTVAw?=
 =?utf-8?B?clNLMWZwUlpqYUc0QjZadXU0bG1wUVJsKzdoMkpaOVNOVU1YR2xFRElBWW1y?=
 =?utf-8?B?dEp2NWh4bWZHLy9BQUFxcEhjWitHZG1PM0p0b2p3MHordWZLemhOcG9pT050?=
 =?utf-8?B?Zm05TDdFL0tVcjhjeDFoSjRrQ3N4VzFwOFpLbjNvNHoxcHlndEoxQUwxbitO?=
 =?utf-8?B?a1ZRdWZpeWN6VnczLzNab05OeVhVOFRRcVRtdFR4Nkg5aGU0VzJLYUxiNG1a?=
 =?utf-8?B?VmQwRUptSDVaaDBIc3FQRzRnbVZMVlM3eWNndUxZeEtTc2RDendOTzJnSUlz?=
 =?utf-8?B?eTZONDdZVitMM2RRZFEzbDNyUEc0bEk5aGNBN250aG9rVG5aZHNzcWFab3Jw?=
 =?utf-8?B?WnRWNEd2U0N1dnQ4bzlScDlSZ0dwbElRclBBOG5PazAxRjJrZVJkbjkzaUhs?=
 =?utf-8?B?UWJxZjBWZTZFTHRGSDhhdEtOS3czOWI2dmNrWE5QS3ZyWXlJZ0pHL3Z6SjFD?=
 =?utf-8?B?NXVFZkRBekx5NWdaZ2ZUQmpERE9oYlIzcVJ4ZGJoSzdYbEFsV2ZJd3ozVEIz?=
 =?utf-8?B?aU10bDJtRXlsNkk3a0R5ZDN6ZkhIMzJyelBjSkVadkU2UXZUeWoxbStjVEUv?=
 =?utf-8?B?ODA3MFpjcnZhUXgvWmd2NnFxWnh0YkZzcmR1QTZYdGp2QzRtdm5QLzVjM3hK?=
 =?utf-8?B?TmFaQ3JPNndVNXA5RkJsdEt2RFFPNWZVTTNab2hlVmNraldnM2lNSnRyQThY?=
 =?utf-8?B?WGNSejIvWDd0Um9lNTJ4QmZUeEFPdzJaRUJDVGNIbDlKUFJYU2F5RUgwQ3dP?=
 =?utf-8?B?OGhmYkZQeHFzTlk1S0EwS1F4bjlxTkdpQ2JmUm9yZWxyYU9odndTVEF6Qkwz?=
 =?utf-8?B?QlEvZ1AzdGQ1Z3ViM2g0Zk55aC9ZWFNsSGt6djUzd0FHUUJhMk8zRzlyeS8z?=
 =?utf-8?B?emw5eDJpTEVBNGcyOUVuZTUva293L2xsNGJ1QlU5M0k0K29UaXI1eFVFbkl6?=
 =?utf-8?B?djVub0FnL3ZXdmxWS3RCRXJOclRXdC92UCtvMVdydElpNGZIaitsbHBiOFNG?=
 =?utf-8?B?UnlGcjdTM203YThRNVpkUmVncHVZcVh2WkZWYVQzV0dpcGYvbVlnWDcwOUZT?=
 =?utf-8?B?RjRCajV1WmhKZCsvemtrZmpsUW1PWXFoYWJXUGhtclFYWE5obmRNOTNTUFRz?=
 =?utf-8?B?YUhVak5tNk85K3Q4OUxMZFNocFRDS0o2SXFyWkYrVHlQSWlyakpIcUdKeWdU?=
 =?utf-8?B?RmxOUGxiV0NMY0Fyb3FSazlPc2h1dFhLUXVVUkxWQ1VzbEZNNmtKNFBESVFN?=
 =?utf-8?B?OHZRTnNCTStFMEo3T05JRXRrM09mSkM4SFpBQUhXd1FTVzBkazdtSUl1d2VV?=
 =?utf-8?B?SHc0Zmx3UFhsd0hZNnFSbjdZOGxGV1lmQ3kwM3VDOFZCRFg3dXQ3UHg3Rytn?=
 =?utf-8?B?amgwZm1ta2Z4QlJmd25lLzFybjE4RG5LakpDYUFKbVpDcFU0YkFYYzNnS3l6?=
 =?utf-8?B?bXpJVnRiTk9GRjJhKzh3YklaMmk1VnhMWUp5aG1aWVJRTE8yS1N5aFdWZEwv?=
 =?utf-8?B?ZEZvSzJQTC8rckJlUkkwVmRWVC9kZ0FRUktybHJsZzluOUpYU2ZwSUllMWJx?=
 =?utf-8?B?L0RCZHgzYThJSFFGd2lMM05lbUxYUlljanUvZU5hMVNTMDAvbFpYdTNkQUpJ?=
 =?utf-8?B?S0F3MTFyUHM4RlJyYlRmS2lIc0ZjQVFBdjJZYzFPbVBFVXhDRXZoQ2FFQWRa?=
 =?utf-8?B?WUVtQUsxakxZY3VGZTk2YnN4ZjkxZXRlQi80aVFia1pUa1ppZWIycWZPS05M?=
 =?utf-8?B?TWo4M3Qzdjlua3BJWTJTeGtpSlRpVkIyYzd3aUgyYm9nZlhNWGxRU0kyeHo0?=
 =?utf-8?B?RytPaVhyMnU3V1k1S3E2aWR4ZHp6TlpVTi9yRmRabXNuU01UYkQwQ0N0MU9i?=
 =?utf-8?B?TjVkNlhpbUZMUlpRTmRIblFCUGwwUy96blBod2lBVENTaHFvRW1EYk1GcFBX?=
 =?utf-8?B?SllZWGNPa0R0dWh5bWMyalNOb3ZtM2ExNW1oUVdjZFJUK2ppS3BTT0FZNHgv?=
 =?utf-8?B?R0F3Q2tTbFlTMkNXU3FrODlhanBPRm4xMzF4SkxKUU4xdDNnVDZyU0N3MzFn?=
 =?utf-8?B?aEZKMHlWc2kyaDFncCtMWkRiSmY2amxVLzN6TzRFVnF0VWZraURhTDhxSWRO?=
 =?utf-8?B?YVN1ek9CYzJkSDE4b1Fla2pMSWhZRmhhMmdiN1JuNm4xOTVsdHBRWVlNUzFH?=
 =?utf-8?B?N1Z1ckFPZjNxK1VHY2YzcVBxNitQR0pmSU9WL05HbjM0d1BZM2x1QlRia0d6?=
 =?utf-8?B?RU5EQStaaEdGUCtjblRrTFNHZE1oQk55MGM5QU5IaVVMcWVxbmttYVlrdkRn?=
 =?utf-8?B?TENUbFk4eEUyWU5sTlZMRlg3RU5OWTd6NmxOTjFRVlQxZVFUbUdyNWc0MEhP?=
 =?utf-8?B?ZENHb3N5b3NhdERpT3MveUNyT3l0bTZ5OUh5QlJ3c1RoUFBWZGI5VDhodHlO?=
 =?utf-8?B?VkVHVDRMZ2FGcFY4T2ZDUG02R3EyVHVlRUxOZEgyNXVEelFLZmZsTnR6UTNk?=
 =?utf-8?B?S0lDK0tDbFlJSlR5Y0p2SHF6MXM4eHYxMkY5SHdvU0pmaHdiWnZwVHRnQzVm?=
 =?utf-8?B?K2NuRjZrUDBDa2JVNElXVmF5MEcxYVpvNUtwWlNMdDhlVnZibFhaaW51d0Z0?=
 =?utf-8?B?bUVCT0F3OEVRWDZwOG4ydTREc29Tbi9hb1pFa2d5VGNJRm4vVWFpWlpzTzNO?=
 =?utf-8?B?Q3RObE1uNjZvMGU0Tkhqak5kTEdkUlZOWmJnZURVN3lIeTByUmFwOHBRcC9m?=
 =?utf-8?B?S1FyL2dkM2J2QVNoRm9ZYnZpTFpJazdqQ3RRZHg5SzBORTUzOEE1clc3b3RK?=
 =?utf-8?B?MitvWExYSXkrRnFwVTZySGFUQ3M4c09weVlBTzYvU3hMZk40SWZ5NmtwU3RZ?=
 =?utf-8?B?QT09?=
MIME-Version: 1.0

[You don't often get email from ijece@iaesjournal.com. Learn why this is im=
portant at https://aka.ms/LearnAboutSenderIdentification ]

The following message is being delivered on behalf of International Journal
of Electrical and Computer Engineering (IJECE).
________________________________________________________________________
Dear Prof/Dr/Mr/Mrs: Engineer Hern=C3=A1n Alveiro Erazo,

Thank you for submitting the manuscript, "An LPWAN Mesh Network for
Agricultural Applications" to International Journal of Electrical and
Computer Engineering (IJECE), an open access and peer-reviewed internationa=
l
journal. With the online journal management system that we are using, you
will be able to track its progress through the editorial process by logging
in to the journal web site:

Manuscript URL:
https://ijece.iaescore.com/index.php/IJECE/author/submission/42218 <-- It i=
s
your paper ID
Username: haerazog
When contacting us, please always include your paper ID number in the
subject line of your email.

Attention Please!
1. Please try to adhere to the format as closely as possible. Please
carefully read our most recent manuscript submission guidelines
(https://iaescore.com/gfa/ijece.docx).
2. Add the names of all authors (by Edit Metadata), and please provide
active or valid emails, as well as author identifiers and academic social
network profiles, such as Google Scholar, ORCID, Scopus, and Web of Science
ResearcherID (formerly Publons). You can also add your Academia.edu,
ResearchGate, LinkedIn, Loop, and other profiles. Please keep in mind that
if you do not supply complete, identical, and correct identities between th=
e
metadata and the actual document, your article will be rejected!!
3. A high quality paper should has:
    a) a clear statement of the problem the paper is addressing;
    b) the proposed solution(s); and
    c) results achieved. It describes clearly what has been done before on
the problem, and what is new. Please clearly state the three points listed
above in your updated paper.
4. The number of minimum references for an original research paper is 25
(and at least 20 recently journal articles); and the number of minimum
references for a review paper is 50 (and at least 40 recently journal
articles).

Thank you for considering this journal as a venue for your work.

Best Regards,
Tole Sutikno
International Journal of Electrical and Computer Engineering (IJECE)
________________________________________________________________________
International Journal of Electrical and Computer Engineering (IJECE)
http://ijece.iaescore.com
